version: '3.8'

services:
  app:
    build: .
    environment:
      REPOS: ${REPOS}
      BRANCHES: ${BRANCHES}
      GITHUB_OWNER: ${GITHUB_OWNER}
      GITHUB_API_TOKEN: ${GITHUB_API_TOKEN}
      MIRO_API_TOKEN: ${MIRO_API_TOKEN}
      MIRO_BOARD_ID: ${MIRO_BOARD_ID}
      REPO_PADDING: ${REPO_PADDING}
      SHAPES_X_PADDING: ${SHAPES_X_PADDING}
      SHAPE_COLOR_NO_TICKETS: ${SHAPE_COLOR_NO_TICKETS}
      SHAPE_COLOR_TICKETS: ${SHAPE_COLOR_NO_TICKETS}
      JIRA_API_URL: ${JIRA_API_URL}
      JIRA_USERNAME: ${JIRA_USERNAME}
      JIRA_API_TOKEN: ${JIRA_API_TOKEN}
      JIRA_BROWSE_URL: ${JIRA_BROWSE_URL}
